# Generated by Django 4.2.6 on 2023-10-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Автор",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "имя",
                    models.CharField(help_text="Введите имя автора", max_length=50),
                ),
                (
                    "фамилия",
                    models.CharField(help_text="Введите фамилию автора", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Жанр",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Название",
                    models.CharField(
                        help_text="Напишите название жанра(Например: Фантастика, Триллер, Приключения и т.д.)",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Язык",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "язык",
                    models.CharField(
                        help_text="Введите язык, на котором написана книга(например: Английский, Французский, Русский и т.д.)",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Книги",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("название", models.CharField(max_length=50)),
                ("описание", models.TextField(help_text="Краткое описание книги")),
                ("год_издания", models.IntegerField()),
                (
                    "автор",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="книги.автор",
                    ),
                ),
                (
                    "жанр",
                    models.ManyToManyField(
                        help_text="Выберите жанр для этой книги", to="книги.жанр"
                    ),
                ),
                (
                    "язык_книги",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="книги.язык",
                    ),
                ),
            ],
        ),
    ]
