# Generated by Django 4.2.6 on 2023-10-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_blogposts"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogposts",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
