# Generated by Django 4.2 on 2024-01-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
